### ISSUE TITLE
Local Environment

### ISSUE THREAD

**Issue by ashishj-optimus** [SimonMarquis/Firebase-Remote-Config-Changes-Notifier#4]
Thank you for the repo. Somehow this is not working as expected on local. Would you mind sharing the steps? Thanks!

**Comment by SimonMarquis** [comment]
@ashishj-optimus can you please share some details about your issue?
Where are you stuck, what is the error message, etc.

**Comment by ashishj-optimus** [comment]
Apologies for late reply, I continuously get `Remote Config Emulator Not Running or not Found`.

**Comment by SimonMarquis** [comment]
Please provide details on how you come up with this error. 
This has probably nothing to do with this project.
